### ISSUE TITLE
CI-built jar only includes linux yoga natives

### ISSUE THREAD

**Issue by Bluexin** [TeamWizardry/LibrarianLib#150]
https://github.com/TeamWizardry/LibrarianLib/blob/05dec695cc04c3810a9a8454ded4b5deeb304b66/modules/facade/build.gradle#L2-L12
along with
https://github.com/TeamWizardry/LibrarianLib/blob/05dec695cc04c3810a9a8454ded4b5deeb304b66/modules/facade/build.gradle#L24-L26
mean only natives for the OS used for the build will get included.
In dev liblib workspaces this is okay, but for the published jars it's not great.

**Comment by Bluexin** [comment]
And even once natives are present, native method lookup fails because of the shading (see [crash](https://gist.github.com/SwissCheese5/22ed47b93db116653f4c35844aa927a9))
```
java.lang.UnsatisfiedLinkError: ll.org.lwjgl.util.yoga.Yoga.YGConfigNew()J
	at ll.org.lwjgl.util.yoga.Yoga.YGConfigNew(Native Method) ~[librarianlib-facade-1.15-SNAPSHOT.jar:5.0.0a2] {re:classloading}
	at com.teamwizardry.librarianlib.facade.layer.GuiLayer.<clinit>(GuiLayer.kt:1740) ~[librarianlib-facade-1.15-SNAPSHOT.jar:5.0.0a2] {re:classloading}
	at com.teamwizardry.librarianlib.facade.FacadeWidget.<init>(FacadeWidget.kt:23) ~[librarianlib-facade-1.15-SNAPSHOT.jar:5.0.0a2] {re:classloading}
	at com.teamwizardry.librarianlib.facade.FacadeScreen.<init>(FacadeScreen.kt:26) ~[librarianlib-facade-1.15-SNAPSHOT.jar:5.0.0a2] {re:classloading}
```

**Comment by thecodewarrior** [comment]
This has been fixed, I'll open up a new issue for the classloading problem
