### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Builderb0y** [TeamWizardry/LibrarianLib#6]
```
java.lang.AbstractMethodError
	at com.teamwizardry.librarianlib.client.core.UnlistedPropertyDebugViewer$debugText$$inlined$sortedBy$1.compare(Comparisons.kt:317)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:352)
	at java.util.TimSort.sort(TimSort.java:216)
	at java.util.Arrays.sort(Arrays.java:1438)
	at kotlin.collections.ArraysKt___ArraysKt.sortWith(_Arrays.kt:13069)
	at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:822)
	at com.teamwizardry.librarianlib.client.core.UnlistedPropertyDebugViewer.debugText(UnlistedPropertyDebugViewer.kt:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_572_UnlistedPropertyDebugViewer_debugText_Text.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:694)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:171)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1370)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

**Comment by thecodewarrior** [comment]
Does his happen reproducibly? Like when looking at a specific block and sneaking?

**Comment by Builderb0y** [comment]
Seems to happen randomly. If my memory is correct, I was in the middle of crafting something last time this happened. So I guess technically I was looking at a TiC crafting station. Can't sneak while a GUI is open though.

**Comment by thecodewarrior** [comment]
Hm... I'll look into it. Has it happened multiple times?

**Comment by Builderb0y** [comment]
Around 3-4 times so far.

**Comment by thecodewarrior** [comment]
Is the F3 menu open when it happens?

**Comment by Builderb0y** [comment]
I don't usually have the F3 menu open, so unlikely. Nevertheless, I'll make a test instance to see if I can reproduce it.

**Comment by Builderb0y** [comment]
Seems to happen when holding ALT while looking at the TiC crafting station. ALT is my push-to-talk key on teamspeak, so that would explain why it seemed to be random before.

**Comment by thecodewarrior** [comment]
Ah, ok. That helps a lot.

**Comment by thecodewarrior** [comment]
I can't reproduce this with the latest version, does it still occur with recent versions of LibrarianLib?

**Comment by Builderb0y** [comment]
Yes, it still occurs with the most recent version of librarian lib and tinkers construct from curseforge. But unlike my last time testing it, it seems to only happen with ALT held AND the F3 menu open now. (previously it crashed with ALT regardless of the F3 menu, if my memory is correct)

**Comment by thecodewarrior** [comment]
Unlisted property viewer removed in 3.0 refactor (0ea244e2).
